


const DINA_TALKS_APPLICATION_BASE_API = process.env.DINA_TALKS_APPLICATION_BASE_API

const DinaTalksApi ={
  AUTH:{
    REGISTRATION: `${DINA_TALKS_APPLICATION_BASE_API}/register`,
    LOGIN: `${DINA_TALKS_APPLICATION_BASE_API}/login`, 
  },
  PUBLISH_BLOG:{
    UPLOAD_BLOG_POST: `${DINA_TALKS_APPLICATION_BASE_API}/publish`,
    EDIT_UPLOAD_BLOG_POST: `${DINA_TALKS_APPLICATION_BASE_API}/editPost`,
    DELETE_BLOG_POST: `${DINA_TALKS_APPLICATION_BASE_API}/deletePost`,
    GET_BLOG_POSTS: `${DINA_TALKS_APPLICATION_BASE_API}/getPosts`,
  }
}

export default DinaTalksApi;